"use client";

import { useMemo, useState } from "react";

type Item = {
  id: string;
  name: string;
  category: string;
  framework: string;
  type: string;
  description: string;
  new?: boolean;
  dependency?: string;
  code: string;
};

const items: Item[] = [
  { id: "magnetic-button", name: "Magnetic Button", category: "Buttons", framework: "React", type: "Hover", description: "A button that gently follows the cursor.", new: true, code: "<MagneticButton strength={0.24}>\n  Get started\n</MagneticButton>" },
  { id: "press-button", name: "Press Feedback", category: "Buttons", framework: "CSS", type: "Click", description: "Tactile, springy feedback for primary actions.", code: ".button:active { transform: scale(.96); }" },
  { id: "tilt-card", name: "Tilt Card", category: "Cards", framework: "React", type: "Hover", description: "A card that responds to pointer position.", code: "<TiltCard maxTilt={8}>\n  <CardContent />\n</TiltCard>" },
  { id: "focus-input", name: "Focus Field", category: "Inputs", framework: "CSS", type: "Focus", description: "An input with a clean animated focus treatment.", code: "input:focus {\n  border-color: #78a9ff;\n  box-shadow: 0 0 0 3px #78a9ff22;\n}" },
  { id: "nav-indicator", name: "Nav Indicator", category: "Navigation", framework: "React", type: "Click", description: "Animated active state for compact navigation.", code: "<NavIndicator items={['Overview', 'Activity', 'Settings']} />" },
  { id: "dots-loader", name: "Dots Loader", category: "Loading", framework: "CSS", type: "Loop", description: "Three staggered dots for quick loading states.", code: "<DotsLoader size={6} delay={120} />" },
  { id: "shine-border", name: "Shine Border", category: "Hover effects", framework: "CSS", type: "Hover", description: "A low-key sweep of light across an outline.", code: "<ShineBorder duration={1.6}>\n  <Card />\n</ShineBorder>" },
  { id: "switch-toggle", name: "Spring Toggle", category: "Toggles", framework: "React", type: "Click", description: "A responsive toggle with a light spring transition.", new: true, code: "<SpringToggle checked={enabled} onChange={setEnabled} />" },
  { id: "context-menu", name: "Context Menu", category: "Menus", framework: "React", type: "Click", description: "A compact context menu with keyboard support.", code: "<ContextMenu items={actions}>\n  <FileRow />\n</ContextMenu>" },
  { id: "smart-tooltip", name: "Smart Tooltip", category: "Tooltips", framework: "React", type: "Hover", description: "A helpful tooltip with a short entry delay.", code: "<Tooltip label=\"Copy to clipboard\">\n  <CopyButton />\n</Tooltip>" },
  { id: "split-text", name: "Split Text", category: "Text effects", framework: "CSS", type: "Enter", description: "A staggered reveal for short interface copy.", code: "<SplitText delay={45}>Ship with confidence</SplitText>" },
  { id: "swipe-row", name: "Swipe Row", category: "Mobile gestures", framework: "React", type: "Drag", description: "A touch-first action row with swipe affordance.", dependency: "motion", code: "<SwipeRow actions={['Archive', 'Delete']}>\n  <Message />\n</SwipeRow>" },
];

const categories = ["All", "Buttons", "Cards", "Inputs", "Navigation", "Loading", "Hover effects", "Click feedback", "Toggles", "Menus", "Tooltips", "Text effects", "Page transitions", "Mobile gestures"];

function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const p: Record<string, string> = { heart: "♡", search: "⌕", copy: "□", sun: "◐", github: "◒", back: "←", code: "</>", grid: "⊞", chevron: "⌄", reset: "↻", desktop: "▣", mobile: "▯", check: "✓", close: "×", sliders: "☷", arrow: "↗" };
  return <span aria-hidden="true" style={{ fontSize: size, lineHeight: 1 }}>{p[name] || "·"}</span>;
}

function Demo({ id, large = false }: { id: string; large?: boolean }) {
  const [on, setOn] = useState(false);
  const [tab, setTab] = useState(0);
  const [pressed, setPressed] = useState(false);
  const cls = `demo ${large ? "demo-large" : ""}`;
  if (id === "magnetic-button") return <div className={cls}><button className="magnetic" onMouseMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); e.currentTarget.style.transform = `translate(${(e.clientX-r.left-r.width/2)*.14}px, ${(e.clientY-r.top-r.height/2)*.14}px)`; }} onMouseLeave={(e) => e.currentTarget.style.transform = ""}>Explore components <span>→</span></button></div>;
  if (id === "press-button") return <div className={cls}><button className="press-btn">Save changes</button></div>;
  if (id === "tilt-card") return <div className={cls}><div className="tilt" onMouseMove={(e) => { const r=e.currentTarget.getBoundingClientRect(); e.currentTarget.style.transform=`perspective(500px) rotateX(${(r.top+r.height/2-e.clientY)/9}deg) rotateY(${(e.clientX-r.left-r.width/2)/9}deg)`; }} onMouseLeave={(e) => e.currentTarget.style.transform=""}><span className="tiny-dot"/> <div><b>Project Mercury</b><small>Updated 2m ago</small></div><span className="demo-arrow">↗</span></div></div>;
  if (id === "focus-input") return <div className={cls}><label className="demo-input"><span>Project name</span><input placeholder="e.g. microkit-web" /></label></div>;
  if (id === "nav-indicator") return <div className={cls}><div className="mini-nav">{["Overview", "Activity", "Settings"].map((x,i)=><button key={x} className={i===tab?"active":""} onClick={()=>setTab(i)}>{x}</button>)}</div></div>;
  if (id === "dots-loader") return <div className={cls}><div className="dots"><i/><i/><i/></div><small>Fetching updates</small></div>;
  if (id === "shine-border") return <div className={cls}><div className="shine"><span>Hover over me</span></div></div>;
  if (id === "switch-toggle") return <div className={cls}><button className={`toggle ${on?"on":""}`} aria-pressed={on} onClick={()=>setOn(!on)}><i/></button><span className="toggle-label">{on?"Notifications on":"Notifications off"}</span></div>;
  if (id === "context-menu") return <div className={cls}><div className="context"><span>design-assets.zip</span><button onClick={()=>setPressed(!pressed)}>•••</button>{pressed && <div className="menu-pop"><button>Download</button><button>Rename</button><button className="danger">Delete</button></div>}</div></div>;
  if (id === "smart-tooltip") return <div className={cls}><div className="tooltip-wrap"><button className="icon-button"><Icon name="copy"/></button><span className="tooltip">Copy link</span></div></div>;
  if (id === "split-text") return <div className={cls}><div className="split">{"Ship with confidence".split(" ").map((x,i)=><span key={x} style={{animationDelay:`${i*90}ms`}}>{x}</span>)}</div></div>;
  if (id === "swipe-row") return <div className={cls}><div className="swipe"><div className="swipe-actions"><b>Archive</b><b>Delete</b></div><div className="mail-row" draggable onDragEnd={(e)=>e.currentTarget.classList.toggle("dragged")}> <span className="avatar">M</span><div><b>Maya Chen</b><small>Latest build is ready for review</small></div><span>⌁</span></div></div></div>;
  return <div className={cls}>Preview</div>;
}

export default function Home() {
  const [selected, setSelected] = useState<Item | null>(null);
  const [category, setCategory] = useState("All");
  const [query, setQuery] = useState("");
  const [framework, setFramework] = useState("All frameworks");
  const [sort, setSort] = useState("Newest");
  const [favorites, setFavorites] = useState<string[]>(() => {
    if (typeof window === "undefined") return [];
    return JSON.parse(localStorage.getItem("microkit-favorites") || "[]");
  });
  const [copied, setCopied] = useState<string | null>(null);
  const [codeTab, setCodeTab] = useState(false);
  const [viewport, setViewport] = useState<"desktop" | "mobile">("desktop");
  const [canvas, setCanvas] = useState<"dark" | "light">("dark");
  const [strength, setStrength] = useState(24);
  const [sidebar, setSidebar] = useState(true);

  const toggleFavorite = (id: string) => setFavorites(prev => { const next = prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]; localStorage.setItem("microkit-favorites", JSON.stringify(next)); return next; });
  const copy = async (id: string, text: string) => { await navigator.clipboard?.writeText(text); setCopied(id); setTimeout(()=>setCopied(null), 1400); };
  const filtered = useMemo(() => items.filter(x => (category === "All" || x.category === category || (category === "Click feedback" && x.type === "Click")) && (framework === "All frameworks" || x.framework === framework) && `${x.name} ${x.category} ${x.type}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "A–Z" ? a.name.localeCompare(b.name) : sort === "Popular" ? (a.id === "magnetic-button" ? -1 : 1) : (a.new === b.new ? 0 : a.new ? -1 : 1)), [category, framework, query, sort]);

  const chooseCategory = (x: string) => { setCategory(x); setSelected(null); };
  if (selected) return <div className="app"><Header query={query} setQuery={setQuery} sidebar={sidebar} setSidebar={setSidebar}/><div className="shell"><Sidebar open={sidebar} active={selected.category} choose={chooseCategory}/><main className="playground-main"><div className="crumb"><button onClick={()=>setSelected(null)}><Icon name="back"/> All interactions</button><span>/</span><span>{selected.category}</span></div><section className="playground-heading"><div><div className="eyebrow">{selected.category} <span>•</span> {selected.framework}</div><h1>{selected.name}</h1><p>{selected.description}</p></div><div className="header-actions"><button className={`square ${favorites.includes(selected.id)?"saved":""}`} onClick={()=>toggleFavorite(selected.id)} aria-label="Save favorite"><Icon name="heart" size={22}/></button><button className="copy-main" onClick={()=>copy(selected.id, selected.code)}><Icon name={copied===selected.id?"check":"copy"}/> {copied===selected.id?"Copied":"Copy code"}</button></div></section><div className="play-tabs"><button className={!codeTab?"active":""} onClick={()=>setCodeTab(false)}>Preview</button><button className={codeTab?"active":""} onClick={()=>setCodeTab(true)}>Code</button></div>{!codeTab ? <div className="play-layout"><section className="canvas-card"><div className="canvas-toolbar"><div className="segmented"><button className={canvas==="dark"?"active":""} onClick={()=>setCanvas("dark")}>Dark</button><button className={canvas==="light"?"active":""} onClick={()=>setCanvas("light")}>Light</button></div><div className="toolbar-right"><div className="segmented"><button className={viewport==="desktop"?"active":""} onClick={()=>setViewport("desktop")}><Icon name="desktop"/></button><button className={viewport==="mobile"?"active":""} onClick={()=>setViewport("mobile")}><Icon name="mobile"/></button></div><button className="reset"><Icon name="reset"/> Reset</button></div></div><div className={`canvas ${canvas} ${viewport}`}><Demo id={selected.id} large/></div><div className="canvas-footer"><span><i className="status-dot"/> Live preview</span><span>⌘ Enter to reset</span></div></section><aside className="control-panel"><div className="control-title"><Icon name="sliders"/> Customize</div><label className="control"><span>Intensity <output>{strength}%</output></span><input type="range" value={strength} onChange={e=>setStrength(+e.target.value)} /></label><label className="control"><span>Duration <output>240ms</output></span><input type="range" defaultValue="45" /></label><label className="control"><span>Label</span><input value="Explore components" readOnly /></label><label className="check-control"><input type="checkbox" defaultChecked/> Enable reduced motion fallback</label></aside></div> : <CodePanel item={selected} copy={copy} copied={copied}/>}<DetailInfo item={selected}/></main></div></div>;

  return <div className="app"><Header query={query} setQuery={setQuery} sidebar={sidebar} setSidebar={setSidebar}/><div className="shell"><Sidebar open={sidebar} active={category} choose={chooseCategory}/><main className="gallery-main"><div className="gallery-header"><div><div className="eyebrow">Library <span>•</span> {category === "All" ? "All interactions" : category}</div><h1>{category === "All" ? "Explore interactions" : category}</h1><p>{filtered.length} {filtered.length === 1 ? "interaction" : "interactions"} ready to copy, adapt, and ship.</p></div><div className="gallery-controls"><label className="inline-search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter results" /></label><select value={framework} onChange={e=>setFramework(e.target.value)}><option>All frameworks</option><option>React</option><option>CSS</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest</option><option>Popular</option><option>A–Z</option></select></div></div><div className="active-filter"><span>{category === "All" ? "All components" : category}</span>{query && <button onClick={()=>setQuery("")}><Icon name="close"/> Clear search</button>}</div><section className="gallery-grid">{filtered.map(item=><article className="interaction-card" key={item.id}><div className="card-preview"><Demo id={item.id}/>{item.new && <span className="new-badge">New</span>}<button className={`favorite ${favorites.includes(item.id)?"saved":""}`} onClick={()=>toggleFavorite(item.id)} aria-label={`Save ${item.name}`}><Icon name="heart" size={20}/></button></div><div className="card-info"><div><h2>{item.name}</h2><p>{item.category}</p></div><div className="card-tools"><button onClick={()=>copy(item.id,item.code)} title="Copy code"><Icon name={copied===item.id?"check":"copy"}/></button><button onClick={()=>setSelected(item)} title="Open playground"><Icon name="arrow"/></button></div></div><div className="card-meta"><span>{item.framework}</span>{item.dependency && <span>+ {item.dependency}</span>}<span className="state-type">{item.type}</span></div></article>)}</section>{!filtered.length && <div className="empty"><Icon name="search" size={28}/><h2>No interactions found</h2><p>Try a different search or clear your filters.</p><button onClick={()=>{setQuery("");setCategory("All");setFramework("All frameworks")}}>Clear all filters</button></div>}</main></div></div>;
}

function Header({ query, setQuery, sidebar, setSidebar }: { query: string; setQuery: (x:string)=>void; sidebar:boolean; setSidebar:(x:boolean)=>void }) { return <header className="topbar"><div className="brand-area"><button className="sidebar-trigger" onClick={()=>setSidebar(!sidebar)} aria-label="Toggle sidebar"><Icon name="grid"/></button><button className="brand" onClick={()=>location.reload()}><i/>MicroKit <span>UI</span></button></div><nav><a className="current">Browse</a><a>Collections</a><a>Submit</a></nav><label className="global-search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search interactions"/><kbd>⌘ K</kbd></label><div className="top-actions"><button aria-label="Switch theme"><Icon name="sun" size={18}/></button><a className="github" href="https://github.com" target="_blank"><Icon name="github"/> <span>GitHub</span></a></div></header> }
function Sidebar({ open, active, choose }: { open:boolean; active:string; choose:(x:string)=>void }) { return <aside className={`sidebar ${open?"":"collapsed"}`}><div className="sidebar-scroll"><div className="side-label">Browse components</div>{categories.map(c=>{const count=c==="All"?items.length:items.filter(x=>x.category===c || (c==="Click feedback" && x.type==="Click")).length; return <button className={active===c?"selected":""} onClick={()=>choose(c)} key={c}><span>{c}</span><em>{count || "—"}</em></button>})}<div className="side-rule"/><div className="side-label">Your library</div><button><span>Favorites</span><em>0</em></button><button><span>Recently viewed</span><em>3</em></button></div><div className="sidebar-bottom"><div className="promo-icon">✦</div><div><b>Free forever</b><span>Copy, customize, ship.</span></div></div></aside> }
function CodePanel({ item, copy, copied }: { item:Item; copy:(id:string,t:string)=>void; copied:string|null }) { return <div className="code-layout"><aside className="code-side"><span className="side-label">On this page</span><a className="selected">Component</a><a>Usage</a><a>Accessibility</a><a>Related</a></aside><section className="code-content"><CodeBlock label="components/magnetic-button.tsx" code={item.code} item={item} copy={copy} copied={copied}/><CodeBlock label="app/page.tsx" code={`import { ${item.name.replaceAll(" ", "")} } from "@/components/${item.id}";\n\nexport default function Page() {\n  return <main>\n    ${item.code.split("\n").map(x=>x.trim()).join("\n    ")}\n  </main>;\n}`} item={item} copy={copy} copied={copied}/></section></div> }
function CodeBlock({ label, code, item, copy, copied }: { label:string; code:string; item:Item; copy:(id:string,t:string)=>void; copied:string|null }) { const id=`${item.id}-${label}`; return <div className="code-block"><div className="code-head"><span><Icon name="code"/> {label}</span><button onClick={()=>copy(id,code)}><Icon name={copied===id?"check":"copy"}/> {copied===id?"Copied":"Copy"}</button></div><pre><code>{code}</code></pre></div> }
function DetailInfo({ item }: { item:Item }) { return <section className="detail-info"><div><h2>Installation</h2><p>{item.dependency ? "This interaction uses a small external dependency for gesture handling." : "No dependencies required. Drop the component into your project."}</p><CodeBlock label="Terminal" code={item.dependency ? `npm install ${item.dependency}` : "# No installation required"} item={item} copy={()=>{}} copied={null}/></div><div><h2>Accessibility</h2><p>Keyboard interactive, with visible focus states and a reduced-motion fallback included by default.</p><div className="a11y-tags"><span>Keyboard</span><span>Focus visible</span><span>Reduced motion</span></div></div><div><h2>Related</h2><div className="related"><button>Press Feedback <Icon name="arrow"/></button><button>Shine Border <Icon name="arrow"/></button></div></div></section> }
